-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Tomahawk Strike plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- tlam plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.tlam then
            env.info("DCSRetribution|Tomahawk Strike plugin - Setting Up")

            if dcsRetribution.plugins.tlam.maxRangeKm then
                TLAM.MaxRangeMeters = dcsRetribution.plugins.tlam.maxRangeKm * 1000
            end
            if dcsRetribution.plugins.tlam.cooldownSeconds then
                TLAM.CooldownSeconds = dcsRetribution.plugins.tlam.cooldownSeconds
            end

            -- Ships come from the same generated list the artillery plugins use, so
            -- the group names stay correct as Retribution renumbers them each turn.
            -- Platforms without cruise missiles register as a no-op.
            local platforms = 0
            for _, data in pairs(dcsRetribution.artilleryGroups.shipArtillery) do
                local callsign = data.callsign
                if not callsign then
                    -- "0001 | BUNNY (Naval Two Ship)" -> "BUNNY (Naval Two Ship)"
                    callsign = string.match(data.groupName, "^%d+%s*|%s*(.+)$")
                end
                if AddTLAMPlatform(data.groupName, callsign) then
                    platforms = platforms + 1
                end
            end

            local observers = 0
            for _, data in pairs(dcsRetribution.forwardObserverUnits) do
                AddTLAMObserver(data.unitName)
                observers = observers + 1
            end
            env.info("DCSRetribution|Tomahawk Strike plugin - Registered "
                .. platforms .. " launch platform(s), " .. observers .. " observer(s) from mission data")

            -- Any player slot may call a strike. Slots report no player name until
            -- someone takes one, so pick them up on a poll.
            local function RegisterPlayersAsObservers()
                for _, side in pairs({coalition.side.RED, coalition.side.BLUE}) do
                    local groups = coalition.getGroups(side)
                    if groups then
                        for _, group in pairs(groups) do
                            for _, unit in pairs(group:getUnits() or {}) do
                                local unitName = unit:getName()
                                if unit:getPlayerName() and TLAM.Observers[unitName] == nil then
                                    AddTLAMObserver(unitName)
                                    env.info("DCSRetribution|Tomahawk Strike plugin - Registered observer " .. unitName)
                                end
                            end
                        end
                    end
                end
                return timer.getTime() + 5
            end
            timer.scheduleFunction(RegisterPlayersAsObservers, nil, timer.getTime() + 3)

            if platforms == 0 then
                env.warning("DCSRetribution|Tomahawk Strike plugin - No cruise missile platforms found, the Tomahawk Strike radio menu will be empty")
            end
        end
    end
end
