-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Ballistic Missile Strike plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- bmstrike plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.bmstrike then
            env.info("DCSRetribution|Ballistic Missile Strike plugin - Setting Up")

            if dcsRetribution.plugins.bmstrike.maxRoundsPerMission then
                BMS.MaxRoundsPerMission = dcsRetribution.plugins.bmstrike.maxRoundsPerMission
            end
            if dcsRetribution.plugins.bmstrike.cooldownSeconds then
                BMS.CooldownSeconds = dcsRetribution.plugins.bmstrike.cooldownSeconds
            end
            if dcsRetribution.plugins.bmstrike.launchTimeoutSeconds then
                BMS.LaunchTimeoutSeconds = dcsRetribution.plugins.bmstrike.launchTimeoutSeconds
            end
            if dcsRetribution.plugins.bmstrike.impactRadiusMeters then
                BMS.ImpactRadiusMeters = dcsRetribution.plugins.bmstrike.impactRadiusMeters
            end
            if dcsRetribution.plugins.bmstrike.maxRangeKm and dcsRetribution.plugins.bmstrike.maxRangeKm > 0 then
                -- 0 leaves each battery on the range from its own unit definition.
                BMS.MaxRangeOverrideMeters = dcsRetribution.plugins.bmstrike.maxRangeKm * 1000
            end
            if dcsRetribution.plugins.bmstrike.preheatLaunchers ~= nil then
                BMS.PreHeatLaunchers = dcsRetribution.plugins.bmstrike.preheatLaunchers
            end
            if dcsRetribution.plugins.bmstrike.reserveForPlayers ~= nil then
                BMS.ReserveForPlayers = dcsRetribution.plugins.bmstrike.reserveForPlayers
            end

            -- Launchers come from the same generated list the artillery plugins use,
            -- so the group names stay correct as Retribution renumbers them each turn.
            -- Groups carrying nothing DCS can fire (the V-1 ramp) register as a no-op.
            local batteries = 0
            for _, data in pairs(dcsRetribution.artilleryGroups.ballisticMissiles) do
                local callsign = data.callsign
                if not callsign then
                    -- "0001 | Iskander Site (Missile Site)" -> "Iskander Site (Missile Site)"
                    callsign = string.match(data.groupName, "^%d+%s*|%s*(.+)$")
                end
                if AddBMBattery(data.groupName, callsign, tonumber(data.maxRangeMeters)) then
                    batteries = batteries + 1
                end
            end

            local observers = 0
            for _, data in pairs(dcsRetribution.forwardObserverUnits) do
                AddBMObserver(data.unitName)
                observers = observers + 1
            end
            env.info("DCSRetribution|Ballistic Missile Strike plugin - Registered "
                .. batteries .. " launcher group(s), " .. observers .. " observer(s) from mission data")

            -- Any player slot may call a strike. Slots report no player name until
            -- someone takes one, so pick them up on a poll.
            local function RegisterPlayersAsObservers()
                for _, side in pairs({coalition.side.RED, coalition.side.BLUE}) do
                    local groups = coalition.getGroups(side)
                    if groups then
                        for _, group in pairs(groups) do
                            for _, unit in pairs(group:getUnits() or {}) do
                                local unitName = unit:getName()
                                if unit:getPlayerName() and BMS.Observers[unitName] == nil then
                                    AddBMObserver(unitName)
                                    env.info("DCSRetribution|Ballistic Missile Strike plugin - Registered observer " .. unitName)
                                end
                            end
                        end
                    end
                end
                return timer.getTime() + 5
            end
            timer.scheduleFunction(RegisterPlayersAsObservers, nil, timer.getTime() + 3)

            if batteries == 0 then
                env.warning("DCSRetribution|Ballistic Missile Strike plugin - No ballistic missile launchers found, the Ballistic Missile Strike radio menu will be empty")
            end
        end
    end
end
