-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for Carsten's Arty Spotter Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- arty plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.arty then
            env.info("DCSRetribution|Carsten's Arty Spotter plugin - Setting Up")

            cg_arty_options.user_fireDelay = dcsRetribution.plugins.arty.user_fireDelay
            cg_arty_options.user_quantity = dcsRetribution.plugins.arty.user_quantity
            cg_arty_options.user_spread = dcsRetribution.plugins.arty.user_spread
            cg_arty_options.user_spottingDistance = dcsRetribution.plugins.arty.user_spottingDistance

            -- The script copied cg_arty_options into locals when it loaded, which
            -- happened before this file ran. Without this the values above are
            -- written to a table nothing reads again.
            cg_arty_applyOptions()

            env.info("DCSRetribution|Carsten's Arty Spotter plugin - Applied settings: "
                .. cg_arty_options.user_quantity .. " rounds, "
                .. cg_arty_options.user_spread .. " m spread, "
                .. cg_arty_options.user_fireDelay .. " s delay, "
                .. cg_arty_options.user_spottingDistance .. " km spotting distance")
        end
    end
end
